### ISSUE TITLE
Either use C++14, or remove 'constexpr'

### ISSUE THREAD

**Issue by mfdorst** [CSUS-LLVM/OptSched#10]
When I first built on MacOS I ran into a problem with [this declaration][problematic-code]. The problem was that I wasn't building with C++14 enabled, and in C++11 and earlier, `std::pair`'s constructor is not `constexpr`. I solved this by having my IDE use C++14, but the issue reared its head again today when I tried to build from the command line.
The real problem seems to be that the rest of LLVM is targeting C++11, while OptSched targets C++14 - _but we don't have that specified in the CMakeLists file_. So CMake (on some platforms, including MacOS) will default to C++11, and our code will not compile. 

We seem to have two choices:
1. Target `C++11` everywhere, and remove the offending `constexpr`, or
2. Explicitly target `C++14`.

I've made two competing branches - you can decide which one to merge.

[problematic-code]: https://github.com/CSUS-LLVM/OptSched/blob/ca7b952a572de990a3ff7218122278216718889f/lib/Wrapper/OptimizingScheduler.cpp#L48

**Comment by kerbowa** [comment]
I suppose since we are trying to be an LLVM plugin we should build with C++11 like LLVM does to avoid future issues. LLVM has support headers which replicate some features from the newer standards e.g. llvm::make_unique.

Ideally we want HeuristicNames[] to be constexpr or evaluated at compile time, but if there is not an easy change to do that I guess we can just remove constexpr.

**Comment by mfdorst** [comment]
Just spitballing, we could make our own pair class, or see if LLCVM
provides one that is constexpr.

**Comment by kerbowa** [comment]
Could be done with some templates I think.

**Comment by mfdorst** [comment]
Totally. I believe the implementation of `std::pair` is trivial - but even that may be overkill, we can just make a struct for that particular case. I’ll look into it.

**Comment by kerbowa** [comment]
[Here](https://github.com/llvm/llvm-project/blob/master/libcxx/include/utility#L62) is the libc++ implementation if you are curious.
Remember that the point is to have the map constructed at compile time. [This](https://stackoverflow.com/questions/16490835/how-to-build-a-compile-time-key-value-store) looks right.

**Comment by kerbowa** [comment]
This could be changed back to constexpr in the develop branch, or anything that is tracking LLVM with a c++14 dependency. This should be refactored anyway, but it seems fine for now.
