### ISSUE TITLE
GitHub workflow checks don't trigger on reformat

### ISSUE THREAD

**Issue by Quincunx271** [CSUS-LLVM/OptSched#110]
As found in [#101](https://github.com/CSUS-LLVM/OptSched/pull/101#issuecomment-668755480), changes done by the GitHub actions bot do not trigger any GitHub checks.

From [the documentation](https://docs.github.com/en/actions/reference/events-that-trigger-workflows):

>Note: You cannot trigger new workflow runs using the GITHUB_TOKEN. For more information, see ["Triggering new workflows using a personal access token."](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token)

It looks like we can fix this by using a personal access token instead of the default GITHUB_TOKEN. Creating such a secret requires admin access: https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets-for-a-repository .

**Comment by Quincunx271** [comment]
Alternative solution: have some kind of `Do: Re-Check` comment command which reruns our checks. May or may not be possible.

**Comment by kerbowa** [comment]
> Alternative solution: have some kind of `Do: Re-Check` comment command which reruns our checks. May or may not be possible.

Feel like we should have this anyway, for the cases where something went wrong with the test machine or something.

**Comment by Quincunx271** [comment]
If something went wrong with the test machine or something, the GitHub UI for the checks has a "Re-run checks" or something to that effect. That will work for that scenario.

**Comment by Quincunx271** [comment]
Sorry, I meant that they have a button to click which reruns the checks.

**Comment by Quincunx271** [comment]
Fixed by #141
