### ISSUE TITLE
CI's ccache doesn't seem to be working

### ISSUE THREAD

**Issue by Quincunx271** [CSUS-LLVM/OptSched#114]
Despite the ccache directory being uploaded/downloaded, it appears that we aren't getting cache hits as expected. We shouldn't have to recompile all of LLVM on every CI check.

**Comment by kerbowa** [comment]
ccache doesn't speed things up as much as you would expect. You still need to check the hash for all those files.

**Comment by Quincunx271** [comment]
ccache does speed things up dramatically. Before this problem, the builds were taking roughly 6 minutes instead of 1 hour and 45 minutes. Besides, the ccache statistics reported are showing ~99% cache miss rate when they were previously showing >90% hit rate.

**Comment by Quincunx271** [comment]
Odd. It appears to be working now.
