### ISSUE TITLE
Squashing Commits

### ISSUE THREAD

**Issue by kerbowa** [CSUS-LLVM/OptSched#16]
I wanted to get opinions on squashing commits before opening pull requests so that commits are more self contained like in LLVM. Should we make this the standard and add CONTRIBUTING.md?

**Comment by mfdorst** [comment]
I have generally been doing that, however when there's dialog and we change things after the fact, it kind of ruins the effect. But I do support that idea. In cases where we update the pull request after the fact, once it's approved you can have us squash them and open a second pull request.

**Comment by kerbowa** [comment]
I think if you squash your commits on the PR branch it will update correctly and show a single commit?

**Comment by vangthao95** [comment]
Squashing commits is a good idea, I will do that from now on.
