### ISSUE TITLE
Unnecessary null checks after new expressions

### ISSUE THREAD

**Issue by Quincunx271** [CSUS-LLVM/OptSched#35]
Regular new expressions never return `nullptr` on allocation failure. Instead, they throw `std::bad_alloc`. There are many places in the codebase where we check the result of a new expression against `NULL` assuming that `NULL` means out of memory:

* https://github.com/CSUS-LLVM/OptSched/blob/0fbca358abb51a9b35d4af443577ef219dc5e465/include/opt-sched/Scheduler/bit_vector.h#L88-L90
* https://github.com/CSUS-LLVM/OptSched/blob/0fbca358abb51a9b35d4af443577ef219dc5e465/include/opt-sched/Scheduler/enumerator.h#L967-L969
* https://github.com/CSUS-LLVM/OptSched/blob/0fbca358abb51a9b35d4af443577ef219dc5e465/include/opt-sched/Scheduler/hash_table.h#L341-L344
* And so on (a quick search yielded 91 results).

All of these ifs do nothing. There are some options to correct these:

* Remove these null checks. If we run out of error, we'll just crash with an unhandled `std::bad_alloc`. This would maintain current behavior.
* Replace these null checks with `try { /* do allocation */ } catch (const std::bad_alloc&) { ... }`.
* Replace these new expressions with non-throwing new expressions: `new (std::nothrow) ReadyList(...)`. This form of new expressions does return `nullptr` on allocation failure. Exceptions may still happen if the constructor for `ReadyList` throws.

**Comment by kerbowa** [comment]
What about replacing these with smart pointers?

**Comment by Quincunx271** [comment]
That would be an excellent idea, but it doesn't change any error handling for allocation failure

**Comment by kerbowa** [comment]
My vote is for removing the checks.
