### ISSUE TITLE
runspec-wrapper-* needs to update "The list schedule" -> "The initial schedule"; And avoiding this class of bug in the future

### ISSUE THREAD

**Issue by Quincunx271** [CSUS-LLVM/OptSched#61]
[This commit](https://github.com/CSUS-LLVM/OptSched/commit/efb291911d3dcfd522a9c61e7135a97acb7e9515#diff-4681df460adddcca76f6d47ad0e7bd65R395) introduced a bug in the runspec-wrapper-* scripts: those scripts look for the regex `The list schedule .* is optimal`, but this commit changes the log message to `The initial schedule ... is optimal`.

To combat future bugs of this kind, I propose we come up with a convention to mark a log message as something we are grepping for in our scripts. For example, this one could be:

```
Logger::Info("<The list schedule> of <length %d> and <cost %d> <is optimal>", ...)
```

That way, we can tell at a glance if the log statement is not just for the human reader, but also for script readers, and what pieces of it must be unchanged (or if they are changed, every relevant script should be updated)

**Comment by Quincunx271** [comment]
Another idea: log JSON, but have the interface to log the event be something like:

```
Logger::Event("EventID", "name", dagName, "length", dagLength, "cost", dagCost);
```

Producing a log output of:

```
EVENT: {"id": "EventID", "name": "Function:Block", "length": 20, "cost": 30}
```

Then, the Python scripts can parse these logs using the standard library module `json`.

**Comment by kerbowa** [comment]
Either sounds good. You could add an option to write the json output to some separate file. That would make it easier to save only the data we care about from a run.

They are good ideas but at least the scripts you guys are currently using would need to be updated to go along.

**Comment by Quincunx271** [comment]
I have changes which use Logger::Event(...) for all the relevant log statements I could find. However, what remains is changing the scripts to parse the new format instead of the old format. I haven't finished doing that yet.
