### ISSUE TITLE
Logs end early for runspec-wrapper-optsched.py, around 1.9 MB

### ISSUE THREAD

**Issue by Quincunx271** [CSUS-LLVM/OptSched#64]
If running runspec-wrapper-optsched.py with the `-w` (writelogs) flag, the log files end at about 1.9 MB.

Is this code bugged?

https://github.com/CSUS-LLVM/OptSched/blob/0bc0d3ec9a16fe76e537637d05e430d51db97b60/util/CPU2006/runspec-wrapper-optsched.py#L734-L740

It seems to me like one of a few things is happening:

 - The subprocess hasn't finished flushing all its output yet
 - So much data is written to the pipe that the OS is buffering, but somehow, the pipe gets closed before we read all of the data from it

Other oddities:

 - At least one of the files is weirdly bugged. All of the unix tools (vim, wc, python, etc) think the file ends at about line 25000 mid-line, but vscode thinks it ends at about 75000, also mid-line.

**Comment by kerbowa** [comment]
Maybe try https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate

**Comment by Quincunx271** [comment]
I haven't repro'd this since. I'm going to close this for now, to reopen if we see the same issue again.
