### ISSUE TITLE
GitHub workflow should enable asserts

### ISSUE THREAD

**Issue by Quincunx271** [CSUS-LLVM/OptSched#81]
.github/workflows/ccpp.yml should build with asserts enabled rather than disabled. It currently does not, because a Debug build takes too much memory and CMake's Release configuration passes `-DNDEBUG`. Ideally, we would still have asserts enabled.

---

I don't plan on working on this yet. However, I figured that documenting this concern with an issue would be best.

**Comment by kerbowa** [comment]
To avoid using too much memory when doing a debug build of LLVM I'd recommend using gold or lld instead of ld. `-DLLVM_USE_LINKER=gold`

Alternatively, if you use ninja instead of make you can limit the number of concurrent link jobs.

**Comment by Quincunx271** [comment]
How to enable asserts on release mode: pass `-DLLVM_ENABLE_ASSERTIONS=ON` when configuring CMake. LLVM knows to pass `-UNDEBUG`, which undoes the `-DNDEBUG`. This also enables the `-debug` and `-debug-only=optsched-ddg-wrapper` flags without needing a Debug build.
