### ISSUE TITLE
GitHub workflow to auto clang-format.

### ISSUE THREAD

**Issue by Quincunx271** [CSUS-LLVM/OptSched#88]
I've noticed a few PRs in the last few days where a clang-format run was forgotten. It's actually possible to have a GitHub workflow do this for us. Is this something that we want?

I have a working yml file I made a while back in experimentation, triggered when the PR author comments "Do: Reformat" (or any other trigger we want). It rewrites history, clang-format-ing each commit.

**Comment by vangthao95** [comment]
This sounds like a nice setup to have.
