### ISSUE TITLE
Debugging scripts from Wiki

### ISSUE THREAD

**Issue by Quincunx271** [CSUS-LLVM/OptSched#89]
I have a couple scripts which aide in debugging mismatches. Are they useful enough to pull into the main repo?

 - [findblock.py](https://github.com/CSUS-LLVM/OptSched/wiki/Debugging#minimize-the-test-case) searches for which benchmark in CPU2006 has the block, by searching through a spills.dat.
 - [ddg2dot.py](https://github.com/CSUS-LLVM/OptSched/wiki/Debugging#visualizing-the-ddg) converts the output of our `DataDepGraph::WriteToFile(...)` function into a `.dot` file which Graphviz's `dot` executable can visualize for us.

**Comment by vangthao95** [comment]
I think they are useful to pull into the main repo.
